Revert "Use shuffle algo by default on \!choose"
This reverts commit 8736185896f5dfb4df0147856f9288b505136847.

Because of this error when choosing teams:
```
Exception: #<TypeError: wrong element type String at 0 (expected array)>
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:1091:in `to_h'
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:1091:in `each'
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:1091:in `map'
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:1091:in `get_fair_teams'
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:933:in `choose_teams'
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:149:in `block (2 levels) in run'
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:916:in `setup_pug'
/discord-bot/lib/qwtf_discord_bot/qwtf_discord_bot_pug.rb:131:in `block in run'
/usr/local/bundle/bundler/gems/discordrb-d238f6f4d1ad/lib/discordrb/commands/parser.rb:108:in `call'
/usr/local/bundle/bundler/gems/discordrb-d238f6f4d1ad/lib/discordrb/commands/command_bot.rb:240:in `execute_command'
/usr/local/bundle/bundler/gems/discordrb-d238f6f4d1ad/lib/discordrb/commands/command_bot.rb:340:in `simple_execute'
/usr/local/bundle/bundler/gems/discordrb-d238f6f4d1ad/lib/discordrb/commands/command_bot.rb:498:in `block in execute_chain'
```